name = "Modded Bridge"
author = "Samuel Wu"
version = "1.1.0+26.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab1ccdff6711fc6a141f7563c9912cf9bbae236be538089e83415579c3b33bad"

[versions]
fabric = "0.18.4"
minecraft = "26.1"
