name = "Modded Bridge"
author = "Samuel Wu"
version = "26.1+mc26.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e76a6788c848f1095245c41d22b3bbc65156bc48a1feede53b9b18ac8e07c7d"

[versions]
fabric = "0.18.6"
minecraft = "26.1"
