name = "Modded Bridge"
author = "Samuel Wu"
version = "26.1+mc1.21.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa05212027cbc8f0a186a9924761a2e523033dbc653a8208fae4cf7bdfafcd60"

[versions]
fabric = "0.18.6"
minecraft = "1.21.1"
