name = "Modded Bridge"
author = "Samuel Wu"
version = "26.3+mc1.21.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22001613b5cfff0cd46a6359b2a78a23d4b8d2bd27bb6f91ac5f7eeea8709762"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
