name = "Modded Bridge"
author = "Samuel Wu"
version = "26.1+mc1.21.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "622ff4f20bfcd234bc6913711d90c29c13a40c3039e9aa24bfb6899af0b29d3f"

[versions]
fabric = "0.18.6"
minecraft = "1.21.11"
