name = "Modded Bridge"
author = "Samuel Wu"
version = "1.1.0+1.21.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bdde9c55d122744e339b2fcc90336a25f93b565d9792339b6c083669956bef32"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
