name = "Modded Bridge"
author = "Samuel Wu"
version = "26.3+mc26.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4840fcf452efc8b5a87dd639c261792974a69386d5b56ba09d34e0ac4457d79"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1"]
