name = "Modded Bridge"
author = "Samuel Wu"
version = "26.3+mc26.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3146971f0554fd9ced2cdf22cc6970d053cdae4d08b0b330732db6312093a118"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1"]
