ignoreList:
  - "minecraft:big_dripleaf_stem"
  - "minecraft:big_dripleaf"
  - "minecraft:bush"
  - "minecraft:crimson_roots"
  - "minecraft:fern"
  - "minecraft:firefly_bush"
  - "minecraft:large_fern"
  - "minecraft:pink_petals"
  - "minecraft:rose_bush"
  - "minecraft:short_dry_grass"
  - "minecraft:sunflower"
  - "minecraft:wildflowers"
